//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathServiceClient.MathServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://learningwcf.com/MathService", ConfigurationName="MathServiceReference.SimpleMath")]
    public interface SimpleMath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://learningwcf.com/MathService/SimpleMath/add", ReplyAction="http://learningwcf.com/MathService/SimpleMath/addResponse")]
        double add(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://learningwcf.com/MathService/SimpleMath/add", ReplyAction="http://learningwcf.com/MathService/SimpleMath/addResponse")]
        System.Threading.Tasks.Task<double> addAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://learningwcf.com/MathService/SimpleMath/addList")]
        void addList(System.Collections.Generic.List<double> numbers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://learningwcf.com/MathService/SimpleMath/addList")]
        System.Threading.Tasks.Task addListAsync(System.Collections.Generic.List<double> numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://learningwcf.com/MathService/SimpleMath/sub", ReplyAction="http://learningwcf.com/MathService/SimpleMath/subResponse")]
        double sub(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://learningwcf.com/MathService/SimpleMath/sub", ReplyAction="http://learningwcf.com/MathService/SimpleMath/subResponse")]
        System.Threading.Tasks.Task<double> subAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://learningwcf.com/MathService/SimpleMath/mul", ReplyAction="http://learningwcf.com/MathService/SimpleMath/mulResponse")]
        double mul(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://learningwcf.com/MathService/SimpleMath/mul", ReplyAction="http://learningwcf.com/MathService/SimpleMath/mulResponse")]
        System.Threading.Tasks.Task<double> mulAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://learningwcf.com/MathService/SimpleMath/div", ReplyAction="http://learningwcf.com/MathService/SimpleMath/divResponse")]
        double div(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://learningwcf.com/MathService/SimpleMath/div", ReplyAction="http://learningwcf.com/MathService/SimpleMath/divResponse")]
        System.Threading.Tasks.Task<double> divAsync(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimpleMathChannel : MathServiceClient.MathServiceReference.SimpleMath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleMathClient : System.ServiceModel.ClientBase<MathServiceClient.MathServiceReference.SimpleMath>, MathServiceClient.MathServiceReference.SimpleMath {
        
        public SimpleMathClient() {
        }
        
        public SimpleMathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleMathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleMathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleMathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double add(double x, double y) {
            return base.Channel.add(x, y);
        }
        
        public System.Threading.Tasks.Task<double> addAsync(double x, double y) {
            return base.Channel.addAsync(x, y);
        }
        
        public void addList(System.Collections.Generic.List<double> numbers) {
            base.Channel.addList(numbers);
        }
        
        public System.Threading.Tasks.Task addListAsync(System.Collections.Generic.List<double> numbers) {
            return base.Channel.addListAsync(numbers);
        }
        
        public double sub(double x, double y) {
            return base.Channel.sub(x, y);
        }
        
        public System.Threading.Tasks.Task<double> subAsync(double x, double y) {
            return base.Channel.subAsync(x, y);
        }
        
        public double mul(double x, double y) {
            return base.Channel.mul(x, y);
        }
        
        public System.Threading.Tasks.Task<double> mulAsync(double x, double y) {
            return base.Channel.mulAsync(x, y);
        }
        
        public double div(double x, double y) {
            return base.Channel.div(x, y);
        }
        
        public System.Threading.Tasks.Task<double> divAsync(double x, double y) {
            return base.Channel.divAsync(x, y);
        }
    }
}
